modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "oracle_index"
version = "${version}"
displayName = "Oracle Index"
authors = "Me! - Rearth"
description = '''
Multiplatform Wiki / Documentation mod for content from moddedmc.org
'''
#logoFile = ""

[[dependencies.oracle_index]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oracle_index]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oracle_index]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oracle_index]]
modId = "owo"
type = "required"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "oracle_index.mixins.json"
